version: '3'

services:

  backups:
    image: python:3.8.2-alpine
    command: boot
    working_dir: ${PROJECT_DIR}
    environment:
      PROJECT_DIR: ${PROJECT_DIR}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - .:${PROJECT_DIR}
      - ./backup-entrypoint.sh:/usr/bin/boot
      - ./restore.py:/usr/bin/restore
      - ./backup.py:/etc/periodic/15min/backup
      # - ./backup.py:/etc/periodic/hourly/backup

  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 28016
      ## in case you'd want to use a separated DB
      # REPLACE_ENV_VARIABLES: "TRUE"
      # ENV_VARIABLE_PREFIX: "CFG_"
      # CFG_DB_HOST: "http://localhost:3306"
      # CFG_DB_NAME: "minecraft"
      # CFG_DB_PASSWORD: "..."
    restart: always
    expose:
      - "28016"

  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - ./rcon:/opt/rcon-web-admin/db
